# Generated by Django 6.0.7 on 2026-07-29 16:41

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='SiteContent',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField()),
                ('locale', models.CharField(default='en', max_length=10)),
                ('title', models.CharField(max_length=255)),
                ('payload', models.JSONField(default=dict)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug', 'locale'],
                'constraints': [models.UniqueConstraint(fields=('slug', 'locale'), name='unique_site_content_slug_locale')],
            },
        ),
    ]
