# Generated by Django 6.0.7 on 2026-07-29 17:01

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='IndustryFocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='IndustrySector',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPage',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('slug', models.SlugField(default='landing-page')),
                ('locale', models.CharField(default='en', max_length=10)),
                ('admin_title', models.CharField(default='Landing page', max_length=255)),
                ('company_name', models.CharField(max_length=255)),
                ('search_placeholder', models.CharField(max_length=255)),
                ('contact_email', models.EmailField(max_length=254)),
                ('contact_phone', models.CharField(max_length=40)),
                ('header_search', models.CharField(default='Search', max_length=80)),
                ('header_contact_aria', models.CharField(max_length=255)),
                ('header_display_aria', models.CharField(max_length=255)),
                ('theme_mode_system_label', models.CharField(default='System', max_length=40)),
                ('theme_mode_light_label', models.CharField(default='Light', max_length=40)),
                ('theme_mode_dark_label', models.CharField(default='Dark', max_length=40)),
                ('hero_eyebrow', models.CharField(max_length=255)),
                ('hero_title', models.TextField()),
                ('hero_description', models.TextField()),
                ('hero_primary_cta', models.CharField(max_length=120)),
                ('hero_secondary_cta', models.CharField(max_length=120)),
                ('delivery_eyebrow', models.CharField(max_length=255)),
                ('delivery_title', models.CharField(max_length=255)),
                ('delivery_badge', models.CharField(max_length=120)),
                ('working_style_eyebrow', models.CharField(max_length=255)),
                ('working_style_title', models.CharField(max_length=255)),
                ('working_style_description', models.TextField()),
                ('services_eyebrow', models.CharField(max_length=255)),
                ('services_title', models.CharField(max_length=255)),
                ('services_description', models.TextField()),
                ('services_overview_eyebrow', models.CharField(max_length=255)),
                ('services_overview_title', models.CharField(max_length=255)),
                ('services_overview_description', models.TextField()),
                ('process_eyebrow', models.CharField(max_length=255)),
                ('process_title', models.CharField(max_length=255)),
                ('process_description', models.TextField()),
                ('work_eyebrow', models.CharField(max_length=255)),
                ('work_title', models.CharField(max_length=255)),
                ('about_eyebrow', models.CharField(max_length=255)),
                ('about_title', models.CharField(max_length=255)),
                ('about_description', models.TextField()),
                ('about_purpose_title', models.CharField(max_length=255)),
                ('about_purpose_description', models.TextField()),
                ('about_values_title', models.CharField(max_length=255)),
                ('about_people_title', models.CharField(max_length=255)),
                ('about_people_description', models.TextField()),
                ('careers_eyebrow', models.CharField(max_length=255)),
                ('careers_title', models.CharField(max_length=255)),
                ('careers_description', models.TextField()),
                ('careers_roles_title', models.CharField(max_length=255)),
                ('careers_cta', models.CharField(max_length=120)),
                ('careers_note', models.TextField()),
                ('contact_eyebrow', models.CharField(max_length=255)),
                ('contact_title', models.TextField()),
                ('contact_description', models.TextField()),
                ('contact_placeholder', models.TextField()),
                ('footer_eyebrow', models.CharField(max_length=255)),
                ('footer_title', models.CharField(max_length=255)),
                ('footer_description', models.TextField()),
                ('footer_company_tag', models.CharField(max_length=120)),
                ('footer_cta', models.CharField(max_length=120)),
                ('footer_quick_links_title', models.CharField(max_length=120)),
                ('footer_service_focus_title', models.CharField(max_length=120)),
                ('footer_contact_title', models.CharField(max_length=120)),
                ('footer_contact_label', models.CharField(max_length=255)),
                ('footer_note', models.TextField()),
                ('footer_legal', models.CharField(max_length=255)),
                ('is_published', models.BooleanField(default=True)),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('updated_at', models.DateTimeField(auto_now=True)),
            ],
            options={
                'ordering': ['slug', 'locale'],
            },
        ),
        migrations.CreateModel(
            name='LandingPageAboutPeopleHighlight',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPageAboutPrinciple',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPageCareerRole',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPageDeliveryCadenceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('phase', models.CharField(max_length=80)),
                ('title', models.CharField(max_length=255)),
                ('text', models.TextField()),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPageFooterQuickLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=120)),
                ('href', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPageFooterServiceFocus',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPageHeroFocusArea',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('text', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPageNavigationLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=120)),
                ('href', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPageProcessStep',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('step', models.CharField(max_length=120)),
                ('summary', models.TextField()),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='LandingPageWorkSample',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=120)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceCategory',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('title', models.CharField(max_length=255)),
                ('description', models.TextField()),
                ('is_featured', models.BooleanField(default=False)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='ServiceItem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('name', models.CharField(max_length=255)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.CreateModel(
            name='WorkSampleTechnology',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=120)),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
        migrations.RemoveConstraint(
            model_name='sitecontent',
            name='unique_site_content_slug_locale',
        ),
        migrations.DeleteModel(
            name='SiteContent',
        ),
        migrations.AddField(
            model_name='industryfocusarea',
            name='industry_sector',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='focus_areas', to='content.industrysector'),
        ),
        migrations.AddConstraint(
            model_name='landingpage',
            constraint=models.UniqueConstraint(fields=('slug', 'locale'), name='unique_landing_page_slug_locale'),
        ),
        migrations.AddField(
            model_name='industrysector',
            name='landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='industry_sectors', to='content.landingpage'),
        ),
        migrations.AddField(
            model_name='landingpageaboutpeoplehighlight',
            name='landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_people_highlights', to='content.landingpage'),
        ),
        migrations.AddField(
            model_name='landingpageaboutprinciple',
            name='landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='about_principles', to='content.landingpage'),
        ),
        migrations.AddField(
            model_name='landingpagecareerrole',
            name='landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='career_roles', to='content.landingpage'),
        ),
        migrations.AddField(
            model_name='landingpagedeliverycadenceitem',
            name='landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='delivery_cadence_items', to='content.landingpage'),
        ),
        migrations.AddField(
            model_name='landingpagefooterquicklink',
            name='landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_quick_links', to='content.landingpage'),
        ),
        migrations.AddField(
            model_name='landingpagefooterservicefocus',
            name='landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_service_focuses', to='content.landingpage'),
        ),
        migrations.AddField(
            model_name='landingpageherofocusarea',
            name='landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='hero_focus_areas', to='content.landingpage'),
        ),
        migrations.AddField(
            model_name='landingpagenavigationlink',
            name='landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='navigation_links', to='content.landingpage'),
        ),
        migrations.AddField(
            model_name='landingpageprocessstep',
            name='landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='process_steps', to='content.landingpage'),
        ),
        migrations.AddField(
            model_name='landingpageworksample',
            name='landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='work_samples', to='content.landingpage'),
        ),
        migrations.AddField(
            model_name='servicecategory',
            name='landing_page',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_categories', to='content.landingpage'),
        ),
        migrations.AddField(
            model_name='serviceitem',
            name='service_category',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='service_items', to='content.servicecategory'),
        ),
        migrations.AddField(
            model_name='worksampletechnology',
            name='work_sample',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='technologies', to='content.landingpageworksample'),
        ),
    ]
