# Generated by Django 6.0.7 on 2026-07-29 17:10

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('content', '0002_industryfocusarea_industrysector_landingpage_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='landingpage',
            name='footer_social_links_title',
            field=models.CharField(default='Social', max_length=120),
        ),
        migrations.CreateModel(
            name='LandingPageFooterSocialLink',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('order', models.PositiveIntegerField(default=0)),
                ('label', models.CharField(max_length=120)),
                ('platform', models.CharField(max_length=40)),
                ('href', models.URLField(blank=True, default='')),
                ('landing_page', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='footer_social_links', to='content.landingpage')),
            ],
            options={
                'ordering': ['order', 'id'],
                'abstract': False,
            },
        ),
    ]
