import {
  technologyCatalog,
  type TechnologySelection,
} from "./technologies-data";

export type TechnologyConstellationDepth = "distant" | "middle" | "near";
export type TechnologyConstellationGlow = "blue" | "cyan" | "gold";
export type TechnologyConstellationPageKind =
  | "home"
  | "about"
  | "insights"
  | "default"
  | "services"
  | "technologies"
  | "contact";
export type TechnologyConstellationViewportKind =
  | "mobile"
  | "tablet"
  | "desktop";

export type TechnologyConstellationBlueprint = {
  slug: string;
  x: number;
  y: number;
  depth: TechnologyConstellationDepth;
  size: number;
  opacity: number;
  blur: number;
  duration: number;
  delay: number;
  movementX: number;
  movementY: number;
  rotation: number;
  parallax: number;
  glow: TechnologyConstellationGlow;
};

export type TechnologyConstellationItem = TechnologySelection &
  TechnologyConstellationBlueprint;

export type TechnologyConstellationPagePreset = {
  desktopCount: number;
  tabletCount: number;
  mobileCount: number;
  opacityMultiplier: number;
  slugs: readonly string[];
};

function constellation(
  blueprint: TechnologyConstellationBlueprint
): TechnologyConstellationBlueprint {
  return blueprint;
}

export const technologyConstellationDepthOrder = [
  "distant",
  "middle",
  "near",
] as const satisfies readonly TechnologyConstellationDepth[];

export const technologyConstellationBlueprints = [
  constellation({
    slug: "openai",
    x: 8,
    y: 13,
    depth: "middle",
    size: 42,
    opacity: 0.082,
    blur: 0,
    duration: 24,
    delay: 0.9,
    movementX: 22,
    movementY: 28,
    rotation: 4,
    parallax: 8,
    glow: "cyan",
  }),
  constellation({
    slug: "google-gemini",
    x: 18,
    y: 17,
    depth: "distant",
    size: 31,
    opacity: 0.06,
    blur: 1.2,
    duration: 29,
    delay: 3.6,
    movementX: 16,
    movementY: 20,
    rotation: 3,
    parallax: 4,
    glow: "blue",
  }),
  constellation({
    slug: "react",
    x: 30,
    y: 18,
    depth: "middle",
    size: 40,
    opacity: 0.076,
    blur: 0,
    duration: 23,
    delay: 1.8,
    movementX: 20,
    movementY: 24,
    rotation: 4,
    parallax: 7,
    glow: "blue",
  }),
  constellation({
    slug: "next-js",
    x: 40,
    y: 17,
    depth: "distant",
    size: 30,
    opacity: 0.05,
    blur: 1.1,
    duration: 31,
    delay: 4.2,
    movementX: 15,
    movementY: 18,
    rotation: 3,
    parallax: 4,
    glow: "blue",
  }),
  constellation({
    slug: "java",
    x: 60,
    y: 16,
    depth: "middle",
    size: 41,
    opacity: 0.078,
    blur: 0,
    duration: 25,
    delay: 2.7,
    movementX: 21,
    movementY: 27,
    rotation: 4,
    parallax: 7,
    glow: "gold",
  }),
  constellation({
    slug: "spring-boot",
    x: 72,
    y: 16,
    depth: "distant",
    size: 33,
    opacity: 0.055,
    blur: 1,
    duration: 30,
    delay: 5.4,
    movementX: 16,
    movementY: 21,
    rotation: 3,
    parallax: 4,
    glow: "cyan",
  }),
  constellation({
    slug: "flutter",
    x: 84,
    y: 18,
    depth: "near",
    size: 56,
    opacity: 0.09,
    blur: 0,
    duration: 22,
    delay: 1.4,
    movementX: 28,
    movementY: 34,
    rotation: 5,
    parallax: 10,
    glow: "blue",
  }),
  constellation({
    slug: "react-native",
    x: 93,
    y: 18,
    depth: "middle",
    size: 38,
    opacity: 0.072,
    blur: 0,
    duration: 24,
    delay: 4.9,
    movementX: 18,
    movementY: 24,
    rotation: 4,
    parallax: 6,
    glow: "blue",
  }),
  constellation({
    slug: "tensorflow",
    x: 10,
    y: 31,
    depth: "middle",
    size: 39,
    opacity: 0.075,
    blur: 0,
    duration: 26,
    delay: 2.1,
    movementX: 20,
    movementY: 26,
    rotation: 4,
    parallax: 7,
    glow: "gold",
  }),
  constellation({
    slug: "pytorch",
    x: 19,
    y: 40,
    depth: "distant",
    size: 32,
    opacity: 0.056,
    blur: 1.4,
    duration: 30,
    delay: 6.3,
    movementX: 15,
    movementY: 19,
    rotation: 3,
    parallax: 4,
    glow: "gold",
  }),
  constellation({
    slug: "angular",
    x: 31,
    y: 39,
    depth: "middle",
    size: 38,
    opacity: 0.072,
    blur: 0,
    duration: 24,
    delay: 3.2,
    movementX: 19,
    movementY: 24,
    rotation: 4,
    parallax: 6,
    glow: "gold",
  }),
  constellation({
    slug: "vue-js",
    x: 40,
    y: 39,
    depth: "middle",
    size: 36,
    opacity: 0.07,
    blur: 0,
    duration: 25,
    delay: 5.1,
    movementX: 19,
    movementY: 24,
    rotation: 4,
    parallax: 6,
    glow: "cyan",
  }),
  constellation({
    slug: "python",
    x: 59,
    y: 30,
    depth: "near",
    size: 54,
    opacity: 0.092,
    blur: 0,
    duration: 21,
    delay: 1.9,
    movementX: 30,
    movementY: 36,
    rotation: 5,
    parallax: 10,
    glow: "blue",
  }),
  constellation({
    slug: "django",
    x: 71,
    y: 30,
    depth: "distant",
    size: 31,
    opacity: 0.052,
    blur: 1.2,
    duration: 31,
    delay: 6.8,
    movementX: 14,
    movementY: 18,
    rotation: 3,
    parallax: 4,
    glow: "cyan",
  }),
  constellation({
    slug: "amazon-web-services",
    x: 82,
    y: 31,
    depth: "middle",
    size: 41,
    opacity: 0.076,
    blur: 0,
    duration: 26,
    delay: 2.5,
    movementX: 21,
    movementY: 27,
    rotation: 4,
    parallax: 7,
    glow: "gold",
  }),
  constellation({
    slug: "microsoft-azure",
    x: 91,
    y: 30,
    depth: "near",
    size: 52,
    opacity: 0.088,
    blur: 0,
    duration: 22,
    delay: 4.6,
    movementX: 27,
    movementY: 32,
    rotation: 5,
    parallax: 9,
    glow: "blue",
  }),
  constellation({
    slug: "langchain",
    x: 11,
    y: 50,
    depth: "distant",
    size: 33,
    opacity: 0.055,
    blur: 1.3,
    duration: 29,
    delay: 7.1,
    movementX: 15,
    movementY: 18,
    rotation: 3,
    parallax: 4,
    glow: "blue",
  }),
  constellation({
    slug: "fastapi",
    x: 29,
    y: 51,
    depth: "middle",
    size: 37,
    opacity: 0.07,
    blur: 0,
    duration: 24,
    delay: 2.9,
    movementX: 19,
    movementY: 24,
    rotation: 4,
    parallax: 6,
    glow: "cyan",
  }),
  constellation({
    slug: "node-js",
    x: 40,
    y: 50,
    depth: "middle",
    size: 39,
    opacity: 0.074,
    blur: 0,
    duration: 25,
    delay: 5.8,
    movementX: 20,
    movementY: 25,
    rotation: 4,
    parallax: 6,
    glow: "blue",
  }),
  constellation({
    slug: "google-cloud-platform",
    x: 61,
    y: 49,
    depth: "middle",
    size: 42,
    opacity: 0.078,
    blur: 0,
    duration: 26,
    delay: 3.8,
    movementX: 22,
    movementY: 26,
    rotation: 4,
    parallax: 7,
    glow: "blue",
  }),
  constellation({
    slug: "docker",
    x: 72,
    y: 50,
    depth: "middle",
    size: 40,
    opacity: 0.075,
    blur: 0,
    duration: 24,
    delay: 1.7,
    movementX: 20,
    movementY: 24,
    rotation: 4,
    parallax: 7,
    glow: "blue",
  }),
  constellation({
    slug: "kubernetes",
    x: 83,
    y: 50,
    depth: "middle",
    size: 39,
    opacity: 0.074,
    blur: 0,
    duration: 25,
    delay: 4.4,
    movementX: 21,
    movementY: 24,
    rotation: 4,
    parallax: 7,
    glow: "blue",
  }),
  constellation({
    slug: "github-actions",
    x: 92,
    y: 49,
    depth: "distant",
    size: 30,
    opacity: 0.05,
    blur: 1.1,
    duration: 32,
    delay: 7.9,
    movementX: 14,
    movementY: 18,
    rotation: 3,
    parallax: 4,
    glow: "blue",
  }),
  constellation({
    slug: "postgresql",
    x: 9,
    y: 73,
    depth: "middle",
    size: 41,
    opacity: 0.075,
    blur: 0,
    duration: 25,
    delay: 3,
    movementX: 20,
    movementY: 24,
    rotation: 4,
    parallax: 7,
    glow: "blue",
  }),
  constellation({
    slug: "mongodb",
    x: 19,
    y: 74,
    depth: "distant",
    size: 31,
    opacity: 0.054,
    blur: 1.3,
    duration: 30,
    delay: 5.7,
    movementX: 14,
    movementY: 18,
    rotation: 3,
    parallax: 4,
    glow: "cyan",
  }),
  constellation({
    slug: "redis",
    x: 30,
    y: 73,
    depth: "middle",
    size: 37,
    opacity: 0.07,
    blur: 0,
    duration: 24,
    delay: 2.3,
    movementX: 19,
    movementY: 24,
    rotation: 4,
    parallax: 6,
    glow: "gold",
  }),
  constellation({
    slug: "power-bi",
    x: 41,
    y: 72,
    depth: "distant",
    size: 32,
    opacity: 0.053,
    blur: 1,
    duration: 29,
    delay: 6,
    movementX: 15,
    movementY: 18,
    rotation: 3,
    parallax: 4,
    glow: "gold",
  }),
  constellation({
    slug: "apache-kafka",
    x: 60,
    y: 73,
    depth: "distant",
    size: 31,
    opacity: 0.052,
    blur: 1.2,
    duration: 30,
    delay: 8.4,
    movementX: 15,
    movementY: 19,
    rotation: 3,
    parallax: 4,
    glow: "blue",
  }),
  constellation({
    slug: "opencv",
    x: 71,
    y: 71,
    depth: "distant",
    size: 30,
    opacity: 0.05,
    blur: 1,
    duration: 31,
    delay: 7,
    movementX: 14,
    movementY: 18,
    rotation: 3,
    parallax: 4,
    glow: "blue",
  }),
  constellation({
    slug: "ethereum",
    x: 82,
    y: 72,
    depth: "middle",
    size: 37,
    opacity: 0.07,
    blur: 0,
    duration: 26,
    delay: 4.1,
    movementX: 19,
    movementY: 24,
    rotation: 4,
    parallax: 6,
    glow: "blue",
  }),
  constellation({
    slug: "arduino",
    x: 91,
    y: 73,
    depth: "middle",
    size: 38,
    opacity: 0.071,
    blur: 0,
    duration: 25,
    delay: 5.2,
    movementX: 18,
    movementY: 23,
    rotation: 4,
    parallax: 6,
    glow: "cyan",
  }),
  constellation({
    slug: "esp32",
    x: 83,
    y: 87,
    depth: "distant",
    size: 29,
    opacity: 0.048,
    blur: 1,
    duration: 32,
    delay: 8.8,
    movementX: 13,
    movementY: 16,
    rotation: 3,
    parallax: 4,
    glow: "gold",
  }),
] as const satisfies readonly TechnologyConstellationBlueprint[];

export const technologyConstellationPagePresets = {
  home: {
    desktopCount: 20,
    tabletCount: 12,
    mobileCount: 8,
    opacityMultiplier: 1,
    slugs: [
      "openai",
      "react",
      "python",
      "docker",
      "amazon-web-services",
      "postgresql",
      "flutter",
      "google-gemini",
      "next-js",
      "java",
      "kubernetes",
      "microsoft-azure",
      "mongodb",
      "power-bi",
      "opencv",
      "ethereum",
      "arduino",
      "langchain",
      "spring-boot",
      "google-cloud-platform",
    ],
  },
  about: {
    desktopCount: 10,
    tabletCount: 6,
    mobileCount: 4,
    opacityMultiplier: 0.55,
    slugs: ["react", "python", "docker", "amazon-web-services", "java", "postgresql", "flutter", "microsoft-azure", "kubernetes", "google-cloud-platform"],
  },
  insights: {
    desktopCount: 4,
    tabletCount: 3,
    mobileCount: 2,
    opacityMultiplier: 0.35,
    slugs: ["react", "python", "docker", "postgresql"],
  },
  default: {
    desktopCount: 18,
    tabletCount: 10,
    mobileCount: 6,
    opacityMultiplier: 0.92,
    slugs: [
      "openai",
      "react",
      "python",
      "docker",
      "amazon-web-services",
      "next-js",
      "java",
      "postgresql",
      "flutter",
      "google-cloud-platform",
      "redis",
      "power-bi",
      "opencv",
      "ethereum",
      "arduino",
      "microsoft-azure",
      "langchain",
      "kubernetes",
    ],
  },
  services: {
    desktopCount: 20,
    tabletCount: 12,
    mobileCount: 8,
    opacityMultiplier: 0.98,
    slugs: [
      "openai",
      "python",
      "langchain",
      "java",
      "spring-boot",
      "node-js",
      "docker",
      "kubernetes",
      "amazon-web-services",
      "microsoft-azure",
      "google-cloud-platform",
      "postgresql",
      "redis",
      "tensorflow",
      "github-actions",
      "fastapi",
      "mongodb",
      "flutter",
      "opencv",
      "power-bi",
    ],
  },
  technologies: {
    desktopCount: 24,
    tabletCount: 14,
    mobileCount: 10,
    opacityMultiplier: 1.04,
    slugs: [
      "openai",
      "google-gemini",
      "tensorflow",
      "pytorch",
      "langchain",
      "react",
      "next-js",
      "angular",
      "java",
      "spring-boot",
      "python",
      "node-js",
      "flutter",
      "amazon-web-services",
      "microsoft-azure",
      "google-cloud-platform",
      "docker",
      "kubernetes",
      "postgresql",
      "mongodb",
      "power-bi",
      "opencv",
      "ethereum",
      "arduino",
    ],
  },
  contact: {
    desktopCount: 8,
    tabletCount: 6,
    mobileCount: 6,
    opacityMultiplier: 0.72,
    slugs: [
      "openai",
      "react",
      "python",
      "amazon-web-services",
      "docker",
      "postgresql",
      "google-cloud-platform",
      "microsoft-azure",
    ],
  },
} as const satisfies Record<
  TechnologyConstellationPageKind,
  TechnologyConstellationPagePreset
>;

const constellationTechnologyMap = new Map<string, TechnologySelection>(
  technologyCatalog.map((technology) => [technology.slug, technology])
);

export const technologyConstellationCatalog =
  technologyConstellationBlueprints.map((blueprint) => {
    const technology = constellationTechnologyMap.get(blueprint.slug);

    if (!technology) {
      throw new Error(
        `Missing technology definition for constellation slug "${blueprint.slug}".`
      );
    }

    return {
      ...technology,
      ...blueprint,
    };
  }) satisfies TechnologyConstellationItem[];

export function getTechnologyConstellationPageKind(
  activeHref?: string
): TechnologyConstellationPageKind {
  if (!activeHref) {
    return "home";
  }

  switch (activeHref) {
    case "/insights":
      return "insights";
    case "/company":
      return "about";
    case "/services":
      return "services";
    case "/technologies":
      return "technologies";
    case "/contact":
      return "contact";
    default:
      return "default";
  }
}
