LANDING_PAGE_CONTENT = {
    "companyName": "AlphaBeastCodeX Private Limited",
    "navigation": [
        {"label": "Company", "href": "#company"},
        {"label": "Services", "href": "#services"},
        {"label": "Solutions", "href": "#solutions"},
        {"label": "Industries", "href": "#industries"},
        {"label": "Technologies", "href": "#technologies"},
        {"label": "Insights", "href": "#insights"},
        {"label": "Careers", "href": "#careers"},
        {"label": "Contact", "href": "#contact"},
    ],
    "header": {
        "search": "Search",
        "contactAria": "Contact AlphaBeastCodeX",
        "displayAria": "Change site theme",
    },
    "display": {
        "themeModes": {
            "system": "System",
            "light": "Light",
            "dark": "Dark",
        }
    },
    "searchPlaceholder": "Search services, platforms and workflows...",
    "contactEmail": "directors@abcx.co.in",
    "contactPhone": "9113543816",
    "hero": {
        "eyebrow": "Senior-led software engineering",
        "title": "Software that moves business forward.",
        "description": "Clear delivery across AI, cloud, mobile, and enterprise systems.",
        "primaryCta": "Start a Project",
        "secondaryCta": "Book a Discovery Call",
        "focusAreas": [
            "AI systems",
            "Enterprise platforms",
            "Cloud delivery",
            "Mobile products",
        ],
    },
    "delivery": {
        "eyebrow": "Example delivery rhythm",
        "title": "Senior-led delivery with fewer surprises.",
        "badge": "Strategy to launch",
        "cadence": [
            {
                "phase": "Week 1",
                "title": "Clarity sprint",
                "text": "Goals, technical reality, and delivery priorities get aligned quickly so the roadmap starts on firm ground.",
            },
            {
                "phase": "Week 3",
                "title": "Validated direction",
                "text": "Interface concepts, architecture choices, and sequencing are concrete enough for sharp feedback instead of guesswork.",
            },
            {
                "phase": "Week 6",
                "title": "Production path",
                "text": "Core flows, infrastructure, and integration edges are underway with a release plan that reflects real complexity.",
            },
            {
                "phase": "Week 10+",
                "title": "Launch and refine",
                "text": "We tighten quality, monitor adoption, and help the next round of decisions happen from evidence rather than noise.",
            },
        ],
    },
    "workingStyle": {
        "eyebrow": "Working style",
        "title": "Product, design, and engineering move in one loop.",
        "description": "Less handoff friction, tighter decisions, and cleaner releases.",
    },
    "servicesSection": {
        "eyebrow": "Services",
        "title": "Services built for delivery.",
        "description": "Choose the capability you need without splitting strategy, engineering, and support.",
        "overviewEyebrow": "Service overview",
        "overviewTitle": "One delivery team across the stack.",
        "overviewDescription": "From product interfaces to infrastructure, the work stays connected and easier to manage.",
        "featuredTitles": [
            "AI & Generative AI",
            "Software Development",
            "Web Development",
            "Mobile App Development",
            "Cloud & DevOps",
            "Cybersecurity",
        ],
        "items": [
            {
                "title": "AI & Generative AI",
                "description": "AI systems that automate work without losing control.",
                "services": [
                    "AI Chatbots",
                    "AI Agents",
                    "Custom LLM Solutions",
                    "Prompt Engineering",
                    "Generative AI Applications",
                    "Computer Vision",
                    "OCR Solutions",
                    "Natural Language Processing (NLP)",
                    "AI Automation",
                    "AI Consulting",
                ],
            },
            {
                "title": "Blockchain",
                "description": "Blockchain where traceability, trust, or asset flow truly matters.",
                "services": [
                    "Smart Contracts",
                    "DApps",
                    "Enterprise Blockchain",
                    "Wallet Integration",
                    "Blockchain Consulting",
                ],
            },
            {
                "title": "BPO, KPO & ITES",
                "description": "Operational support backed by disciplined process and useful systems.",
                "services": [
                    "Technical Support",
                    "Customer Support",
                    "Back Office Operations",
                    "Data Processing",
                    "Research & Analytics",
                    "Business Process Outsourcing",
                ],
            },
            {
                "title": "Cloud & DevOps",
                "description": "Cloud delivery with cleaner releases and stronger operations.",
                "services": [
                    "Cloud Migration",
                    "AWS Solutions",
                    "Microsoft Azure",
                    "Google Cloud Platform",
                    "DevOps Implementation",
                    "CI/CD Pipelines",
                    "Docker & Kubernetes",
                    "Infrastructure Management",
                ],
            },
            {
                "title": "Cybersecurity",
                "description": "Security built into architecture, testing, and release flow.",
                "services": [
                    "Vulnerability Assessment",
                    "Penetration Testing",
                    "Security Consulting",
                    "Secure Application Development",
                    "Security Audits",
                    "Identity & Access Management",
                ],
            },
            {
                "title": "Data & Analytics",
                "description": "Data pipelines and dashboards built for clearer decisions.",
                "services": [
                    "Business Intelligence",
                    "Power BI Dashboards",
                    "Tableau Dashboards",
                    "Data Engineering",
                    "Data Warehousing",
                    "Data Visualization",
                    "Predictive Analytics",
                ],
            },
            {
                "title": "Digital Transformation",
                "description": "Legacy workflows redesigned for speed, clarity, and scale.",
                "services": [
                    "Business Process Automation",
                    "Legacy Modernization",
                    "Digital Strategy",
                    "Enterprise Transformation",
                ],
            },
            {
                "title": "Enterprise Integration",
                "description": "Systems connected so data moves cleanly across the business.",
                "services": [
                    "API Integration",
                    "ERP Integration",
                    "CRM Integration",
                    "Payment Gateway Integration",
                    "Third-Party Integrations",
                ],
            },
            {
                "title": "Internet of Things (IoT)",
                "description": "Connected devices and dashboards for real-time visibility.",
                "services": [
                    "Smart Device Solutions",
                    "Industrial IoT",
                    "Sensor Integration",
                    "IoT Dashboards",
                    "Remote Monitoring",
                ],
            },
            {
                "title": "IT Consulting",
                "description": "Technical direction shaped around delivery, architecture, and growth.",
                "services": [
                    "Technology Consulting",
                    "Software Architecture",
                    "Digital Strategy",
                    "CTO as a Service",
                    "Product Consulting",
                ],
            },
            {
                "title": "Machine Learning",
                "description": "Machine learning applied where prediction creates real value.",
                "services": [
                    "Predictive Models",
                    "Deep Learning",
                    "Recommendation Systems",
                    "Fraud Detection",
                    "MLOps",
                    "Model Deployment",
                ],
            },
            {
                "title": "Managed IT Services",
                "description": "Steady infrastructure and user support without extra noise.",
                "services": [
                    "IT Infrastructure Management",
                    "Remote IT Support",
                    "Server Management",
                    "Annual Maintenance Contracts (AMC)",
                    "Help Desk Services",
                    "Performance Monitoring",
                ],
            },
            {
                "title": "Mobile App Development",
                "description": "Mobile products that stay polished as they grow.",
                "services": [
                    "Android Apps",
                    "iOS Apps",
                    "Flutter Apps",
                    "React Native Apps",
                    "Hybrid Apps",
                    "Enterprise Mobile Applications",
                ],
            },
            {
                "title": "Quality Assurance & Testing",
                "description": "Testing that reduces release risk and improves confidence.",
                "services": [
                    "Manual Testing",
                    "Automation Testing",
                    "Performance Testing",
                    "Security Testing",
                    "API Testing",
                    "Mobile App Testing",
                ],
            },
            {
                "title": "Software Development",
                "description": "Custom software shaped around your operating model.",
                "services": [
                    "Custom Software Development",
                    "Enterprise Software",
                    "SaaS Product Development",
                    "Product Engineering",
                    "Desktop Applications",
                    "API Development",
                    "Software Modernization",
                    "Legacy System Migration",
                ],
            },
            {
                "title": "Support & Maintenance",
                "description": "Post-launch support that keeps systems stable and improving.",
                "services": [
                    "Software Maintenance",
                    "Application Support",
                    "Version Upgrades",
                    "Bug Fixes",
                    "Performance Optimization",
                    "Security Updates",
                ],
            },
            {
                "title": "Training & Internship",
                "description": "Hands-on training programs that build practical capability.",
                "services": [
                    "Corporate Training",
                    "AI & Machine Learning Training",
                    "Python Development",
                    "Cloud Computing",
                    "Cybersecurity Training",
                    "Data Analytics",
                    "Internship Programs",
                    "Workshops & Bootcamps",
                ],
            },
            {
                "title": "UI/UX Design",
                "description": "Interfaces and flows shaped for clarity and real use.",
                "services": [
                    "UI Design",
                    "UX Research",
                    "Wireframing",
                    "Prototyping",
                    "Design Systems",
                    "Brand Identity",
                ],
            },
            {
                "title": "Web Development",
                "description": "Web experiences built for speed, trust, and usability.",
                "services": [
                    "Corporate Websites",
                    "E-commerce Websites",
                    "Web Portals",
                    "Progressive Web Apps (PWA)",
                    "CMS Development",
                    "Website Maintenance",
                    "Website Redesign",
                ],
            },
        ],
    },
    "industryCatalog": [
        {
            "title": "Banking, Finance & Insurance",
            "services": [
                "Digital banking platforms",
                "Lending and loan workflow systems",
                "Insurance claims and policy portals",
                "Fraud monitoring and compliance tooling",
                "Customer onboarding and KYC journeys",
            ],
        },
        {
            "title": "Education & EdTech",
            "services": [
                "Learning management systems",
                "Student and faculty portals",
                "Assessment and certification workflows",
                "Virtual classroom experiences",
                "Education reporting dashboards",
            ],
        },
        {
            "title": "Energy, Utilities & Telecom",
            "services": [
                "Remote monitoring dashboards",
                "Smart metering and device integration",
                "Field service management platforms",
                "Usage and billing analytics",
                "Network operations tooling",
            ],
        },
        {
            "title": "Healthcare & Life Sciences",
            "services": [
                "Patient portals and appointment systems",
                "Telemedicine and care coordination tools",
                "EMR/EHR integrations",
                "Medical imaging and AI diagnostics support",
                "Healthcare analytics dashboards",
            ],
        },
        {
            "title": "Logistics & Supply Chain",
            "services": [
                "Fleet and route management",
                "Warehouse and fulfillment systems",
                "Shipment tracking portals",
                "Vendor coordination workflows",
                "Delivery performance analytics",
            ],
        },
        {
            "title": "Manufacturing & Industrial",
            "services": [
                "Factory operations dashboards",
                "Production planning and workflow tools",
                "Industrial IoT monitoring systems",
                "Predictive maintenance platforms",
                "Supply chain visibility solutions",
            ],
        },
        {
            "title": "Media, Entertainment & OTT",
            "services": [
                "Content platforms and streaming experiences",
                "Subscription and membership systems",
                "Audience analytics dashboards",
                "Advertising and campaign tooling",
                "Digital asset management workflows",
            ],
        },
        {
            "title": "Public Sector & Smart Cities",
            "services": [
                "Citizen service portals",
                "Department workflow automation",
                "Document digitization and OCR pipelines",
                "Smart infrastructure dashboards",
                "Public data reporting tools",
            ],
        },
        {
            "title": "Real Estate & PropTech",
            "services": [
                "Property listing and booking platforms",
                "Broker and channel partner dashboards",
                "Tenant and facility management tools",
                "Real estate CRM integrations",
                "Location intelligence and portfolio analytics",
            ],
        },
        {
            "title": "Retail & E-commerce",
            "services": [
                "Online storefronts and marketplace platforms",
                "Inventory and order management systems",
                "Loyalty and customer engagement apps",
                "Recommendation engines",
                "Retail analytics and merchandising dashboards",
            ],
        },
        {
            "title": "Agriculture & Agritech",
            "services": [
                "Farm operations dashboards",
                "Sensor-based field monitoring",
                "Supply and procurement systems",
                "Crop planning and reporting tools",
                "Agritech analytics platforms",
            ],
        },
        {
            "title": "Travel, Hospitality & Leisure",
            "services": [
                "Reservation and booking platforms",
                "Guest experience apps",
                "Property operations systems",
                "Dynamic pricing and demand analytics",
                "Service request and concierge workflows",
            ],
        },
    ],
    "processSection": {
        "eyebrow": "Process",
        "title": "A process teams can follow.",
        "description": "Each phase stays visible, practical, and easy to act on.",
        "steps": [
            {
                "step": "Discover",
                "summary": "Understand the challenge.",
            },
            {
                "step": "Design",
                "summary": "Shape the solution.",
            },
            {
                "step": "Develop",
                "summary": "Build with precision.",
            },
            {
                "step": "Launch",
                "summary": "Deploy with confidence.",
            },
            {
                "step": "Support",
                "summary": "Grow continuously.",
            },
        ],
    },
    "workSection": {
        "eyebrow": "Featured work",
        "title": "Selected work shaped by real needs.",
        "samples": [
            {
                "label": "Operations Platform",
                "title": "Connected workflows. Better decisions.",
                "description": "One workspace for approvals, reporting, and coordination.",
                "stack": ["Next.js", "Node APIs", "Role-based UX"],
            },
            {
                "label": "AI Assistant",
                "title": "Knowledge delivered instantly.",
                "description": "Grounded answers with review paths for edge cases.",
                "stack": ["LLM orchestration", "RAG", "Review workflow"],
            },
            {
                "label": "Customer Portal",
                "title": "Built for speed and simplicity.",
                "description": "A legacy portal rebuilt around clearer self-service.",
                "stack": ["Design system", "Modern frontend", "Migration planning"],
            },
        ],
    },
    "aboutSection": {
        "eyebrow": "About",
        "title": "Building for a billion Indians",
        "description": "Technology built to serve real users at meaningful scale with clarity, reliability, and long-term thinking.",
        "purpose": {
            "title": "Purpose",
            "description": "Make complex delivery easier to understand, operate, and extend.",
        },
        "valuesTitle": "What matters",
        "principles": [
            {
                "title": "Senior-led delivery",
                "description": "The people making decisions stay close to the work.",
            },
            {
                "title": "Clear communication",
                "description": "Progress, risk, and tradeoffs stay visible.",
            },
            {
                "title": "Long-term ownership",
                "description": "Teams can take over with confidence after launch.",
            },
        ],
        "people": {
            "title": "Our people",
            "description": "Product, design, and engineering people who stay practical, calm, and close to the problem.",
            "items": [
                "Senior execution from discovery through launch",
                "Cross-functional collaboration without noise",
                "Client-facing builders who own outcomes",
            ],
        },
    },
    "careersSection": {
        "eyebrow": "Careers",
        "title": "Build products that matter.",
        "description": "Join a team that values clear thinking and responsible delivery.",
        "rolesTitle": "What we value",
        "roles": [
            "Engineers who move from architecture to shipped detail",
            "Design-minded builders who care about usability",
            "People who communicate tradeoffs early",
        ],
        "cta": "Share your profile",
        "note": "Send a resume, portfolio, or short introduction.",
    },
    "contactSection": {
        "eyebrow": "Contact",
        "title": "Let's build something meaningful together.",
        "description": "Bring the problem, timeline, or pressure point. We'll help shape the next step.",
        "placeholder": "Email is the fastest way to start.",
    },
    "footer": {
        "eyebrow": "AlphaBeastCodeX",
        "title": "Clear software delivery for ambitious teams.",
        "description": "AI, cloud, product, and platform work delivered with calm ownership.",
        "companyTag": "Software company",
        "cta": "Start a conversation",
        "quickLinksTitle": "Quick links",
        "quickLinks": [
            {"label": "Company", "href": "#company"},
            {"label": "Services", "href": "#services"},
            {"label": "Solutions", "href": "#solutions"},
            {"label": "Industries", "href": "#industries"},
            {"label": "Technologies", "href": "#technologies"},
            {"label": "Insights", "href": "#insights"},
            {"label": "Careers", "href": "#careers"},
            {"label": "Contact", "href": "#contact"},
        ],
        "serviceFocusTitle": "Service focus",
        "serviceFocus": [
            "AI & Generative AI",
            "Software Development",
            "Web Development",
            "Mobile App Development",
            "Cloud & DevOps",
            "Cybersecurity",
        ],
        "contactTitle": "Contact",
        "contactLabel": "Reach out directly",
        "socialLinksTitle": "Social",
        "socialLinks": [
            {"label": "Instagram", "platform": "instagram", "href": ""},
            {"label": "Twitter", "platform": "twitter", "href": ""},
            {"label": "Facebook", "platform": "facebook", "href": ""},
            {
                "label": "WhatsApp",
                "platform": "whatsapp",
                "href": "https://wa.me/919113543816",
            },
            {"label": "LinkedIn", "platform": "linkedin", "href": ""},
        ],
        "note": "Built for clear communication and reliable execution.",
        "legal": "AlphaBeastCodeX Private Limited. All rights reserved.",
    },
}
